
import { GoogleGenAI } from "@google/genai";
import { ImageData } from "../types";

const MODEL_NAME = 'gemini-2.5-flash-image';

export async function editImage(
  originalImage: ImageData,
  prompt: string
): Promise<string> {
  const apiKey = process.env.API_KEY;
  if (!apiKey) {
    throw new Error("API Key not found in environment variables.");
  }

  const ai = new GoogleGenAI({ apiKey });
  
  // Clean up base64 prefix if present
  const base64Data = originalImage.base64.split(',')[1] || originalImage.base64;

  try {
    const response = await ai.models.generateContent({
      model: MODEL_NAME,
      contents: {
        parts: [
          {
            inlineData: {
              data: base64Data,
              mimeType: originalImage.mimeType,
            },
          },
          {
            text: prompt,
          },
        ],
      },
    });

    if (!response.candidates || response.candidates.length === 0) {
      throw new Error("No response generated by the AI.");
    }

    const parts = response.candidates[0].content.parts;
    
    // Find the image part in the response
    for (const part of parts) {
      if (part.inlineData) {
        return `data:image/png;base64,${part.inlineData.data}`;
      }
    }

    // If no image part found, maybe it returned text error?
    const textPart = parts.find(p => p.text);
    if (textPart) {
      throw new Error(textPart.text || "Failed to edit image.");
    }

    throw new Error("The AI did not return an edited image.");
  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
}
